sudo: required

language: ruby

services:
  - docker

script:
  - ./build_version.sh $PHP_VERSION
  - docker run --rm -it exozet/php-fpm:${PHP_VERSION} php -i
  - docker run --rm -it exozet/php-fpm:${PHP_VERSION} php -v

env:
  - PHP_VERSION=5.5.38 PHP_VERSION_ALIAS=5.5

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  script: ./push_version.sh ${PHP_VERSION} ${PHP_VERSION_ALIAS}
  on:
    branch: master
